---
# This file for running locally against the repo itself for development.
# See README.md for how to use this hook in your project.

repos:
  - repo: .
    rev: HEAD
    hooks:
      - id: polymath-general
      - id: polymath-python
      - id: polymath-cpp
      - id: polymath-shell
      - id: polymath-cmake
      - id: polymath-docker
      - id: polymath-markdown
      - id: polymath-xml
      - id: polymath-yaml
      - id: polymath-toml
      - id: polymath-json
      - id: polymath-copyright
        args: [--license, Apache-2.0, --copyright-org, 'Polymath Robotics, Inc.', --reuse-style]
