#!/bin/bash

# Copyright (c) 2025-present Polymath Robotics, Inc. All rights reserved
# Proprietary. Any unauthorized copying, distribution, or modification of this software is strictly prohibited.
set -euxo pipefail

if ! command -v pre-commit >/dev/null 2>&1; then
  echo "pre-commit is not installed. Please install it first."
  exit 1
fi

target_repo="$1"
if [ -z "$target_repo" ]; then
  echo "Usage: $0 <target_repo>"
  exit 1
fi

THIS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cp "$THIS_DIR/.pre-commit-config.yaml" "$target_repo/.pre-commit-config.yaml"
cp "$THIS_DIR/.ruff.toml" "$target_repo/.ruff.toml"
cp "$THIS_DIR/.cpplint.cfg" "$target_repo/.cpplint.cfg"
cp -r "$THIS_DIR/.config/" "$target_repo"

pushd "${target_repo}"
pre-commit install
popd
