---
name: Test Polymath Code Standard

on:
  push:
    branches: [main]
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    name: standardize thyself
    steps:
      - uses: actions/checkout@v6
      - run: python -m pip install pre-commit
        shell: bash
      - run: python -m pip freeze --local
        shell: bash
      - run: pre-commit run --show-diff-on-failure --color=always
        shell: bash

  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
      - run: uv sync
      - run: uv run pytest
